
/* ============================================================
   SQL Exploratory Data Analysis (EDA) Project
   Author: Wickliff
   Purpose: Explore retail sales data in dbo.gold schema
   ============================================================ */

/* ------------------------------------------------------------
   1. DATABASE EXPLORATION
   ------------------------------------------------------------ */
-- List all tables in the database
SELECT * 
FROM INFORMATION_SCHEMA.TABLES;

-- Explore columns in the customers dimension table
SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

/* ------------------------------------------------------------
   2. DIMENSIONS EXPLORATION
   ------------------------------------------------------------ */
-- Explore countries where customers came from
SELECT DISTINCT country 
FROM dbo.[gold.dim_customers];

-- Explore product categories, subcategories, and product names
SELECT DISTINCT category, subcategory, product_name 
FROM dbo.[gold.dim_products]
ORDER BY category, subcategory, product_name;

/* ------------------------------------------------------------
   3. DATE EXPLORATION
   ------------------------------------------------------------ */
-- Find first and last order dates, and range in years
SELECT MIN(order_date) AS first_order_date,
       MAX(order_date) AS last_order_date,
       DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS order_range_years
FROM dbo.[gold.fact_sales];

-- Find youngest and oldest customers
SELECT MIN(birthdate) AS oldest_birthdate,
       MAX(birthdate) AS youngest_birthdate,
       DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
       DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM dbo.[gold.dim_customers];

/* ------------------------------------------------------------
   4. MEASURES EXPLORATION
   ------------------------------------------------------------ */
-- Total sales
SELECT SUM(sales_amount) AS total_sales 
FROM dbo.[gold.fact_sales];

-- Total items sold
SELECT SUM(quantity) AS total_items 
FROM dbo.[gold.fact_sales];

-- Average selling price
SELECT AVG(price) AS avg_price 
FROM dbo.[gold.fact_sales];

-- Total number of orders
SELECT COUNT(DISTINCT order_number) AS total_orders 
FROM dbo.[gold.fact_sales];

-- Total number of products
SELECT COUNT(DISTINCT product_key) AS total_products 
FROM dbo.[gold.dim_products];

-- Total number of customers
SELECT COUNT(DISTINCT customer_number) AS total_customers 
FROM dbo.[gold.dim_customers];

-- Total number of customers who placed an order
SELECT COUNT(DISTINCT customer_key) AS customers_who_ordered
FROM dbo.[gold.fact_sales];

/* ------------------------------------------------------------
   5. BUSINESS METRICS REPORT
   ------------------------------------------------------------ */
-- Generate a unified KPI report
SELECT 'Total_sales' AS measure_name, SUM(sales_amount) AS measure_value 
FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total_quantities', SUM(quantity) 
FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Average_price', AVG(price) 
FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total_orders', COUNT(DISTINCT order_number) 
FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Number_of_products', COUNT(DISTINCT product_key) 
FROM dbo.[gold.dim_products]
UNION ALL
SELECT 'Number_of_customers', COUNT(DISTINCT customer_number) 
FROM dbo.[gold.dim_customers];

/* ------------------------------------------------------------
   6. MAGNITUDE ANALYSIS
   ------------------------------------------------------------ */
-- Total customers by country
SELECT country, COUNT(customer_key) AS total_customers
FROM dbo.[gold.dim_customers]
GROUP BY country
ORDER BY total_customers DESC;

-- Total customers by gender
SELECT gender, COUNT(customer_key) AS total_customers
FROM dbo.[gold.dim_customers]
GROUP BY gender
ORDER BY total_customers DESC;

-- Total products by category
SELECT category, COUNT(product_number) AS product_count
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY product_count DESC;

-- Average costs in each category
SELECT category, AVG(cost) AS avg_cost
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY avg_cost DESC;

-- Total revenue generated by each category
SELECT p.category, SUM(f.sales_amount) AS total_revenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_products] p
  ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Total revenue generated by each customer
SELECT c.customer_key, c.first_name, c.last_name,
       SUM(f.sales_amount) AS total_revenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
  ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- Distribution of items sold across countries
SELECT c.country, SUM(f.quantity) AS total_items_sold
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
  ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;

/* ------------------------------------------------------------
   7. RANKING ANALYSIS
   ------------------------------------------------------------ */
-- Top 5 products generating highest revenue
SELECT TOP 5 p.product_name, SUM(f.sales_amount) AS total_revenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_products] p
  ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- Bottom 5 products (worst performing by revenue)
SELECT TOP 5 p.product_name, SUM(f.sales_amount) AS total_revenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_products] p
  ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;

